name: deploy AST explorer
run-name: Deploy AST explorer
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy AST explorer from linux
    timeout-minutes: 3
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup zig environment"
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.x
      - name: "Run build wasm"
        run: zig build wasm
