name: zlinter-windows-tests
run-name: Windows Tests
on:
  push:
    branches:
      - main
      - 0.14.x
      - 0.14.x-windows-action
jobs:
  test:
    runs-on: windows-latest
    name: Test Windows
    timeout-minutes: 3
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup zig environment"
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: "Run unit tests"
        run: zig build unit-test
      - name: "Run integration tests"
        run: zig build integration-test
      - name: "Run linter"
        run: zig build lint -- src/ *.zig integration_tests/*.zig
